// Curated artworks for the Lumen Gallery exhibition
// Images fetched live from the Met Museum Open Access API (no key required)

export const artworks = [
  {
    id: 1,
    metId: 436535,
    title: "Wheat Field with Cypresses",
    artist: "Vincent van Gogh",
    year: "1889",
    medium: "Oil on canvas",
    dimensions: "73.2 × 93.4 cm",
    style: "Post-Impressionism",
    origin: "Netherlands",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/256px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg",
    description: "Painted during van Gogh's stay at the Saint-Paul-de-Mausole asylum, this canvas pulses with the swirling energy that defined his final period.",
  },
  {
    id: 2,
    metId: 437984,
    title: "Self-Portrait with a Straw Hat",
    artist: "Vincent van Gogh",
    year: "1887",
    medium: "Oil on canvas",
    dimensions: "40.6 × 31.8 cm",
    style: "Post-Impressionism",
    origin: "Netherlands",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/256px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg",
    description: "One of over thirty self-portraits van Gogh made in Paris, showing his rapid adoption of Impressionist colour and broken brushwork.",
  },
  {
    id: 3,
    metId: 436529,
    title: "Irises",
    artist: "Vincent van Gogh",
    year: "1890",
    medium: "Oil on canvas",
    dimensions: "92.7 × 73.9 cm",
    style: "Post-Impressionism",
    origin: "Netherlands",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/256px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg",
    description: "Painted in the last months of his life, van Gogh's irises blaze with colour against a warm yellow ground.",
  },
  {
    id: 4,
    metId: 438817,
    title: "Sunflowers",
    artist: "Vincent van Gogh",
    year: "1887",
    medium: "Oil on canvas",
    dimensions: "43.2 × 61 cm",
    style: "Post-Impressionism",
    origin: "Netherlands",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/256px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg",
    description: "An early study of cut sunflowers painted in Paris, demonstrating van Gogh's bold approach to colour and composition.",
  },
  {
    id: 5,
    metId: 435809,
    title: "Madame Cézanne in a Red Dress",
    artist: "Paul Cézanne",
    year: "c. 1888–1890",
    medium: "Oil on canvas",
    dimensions: "116.5 × 89.5 cm",
    style: "Post-Impressionism",
    origin: "France",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Paul_C%C3%A9zanne_261.jpg/256px-Paul_C%C3%A9zanne_261.jpg",
    description: "One of a series of portraits of his wife Hortense, this work reveals Cézanne's analytical approach to form.",
  },
  {
    id: 6,
    metId: 436121,
    title: "Young Woman with a Water Pitcher",
    artist: "Johannes Vermeer",
    year: "c. 1662",
    medium: "Oil on canvas",
    dimensions: "45.7 × 40.6 cm",
    style: "Dutch Golden Age",
    origin: "Netherlands",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Johannes_Vermeer_-_Wikipedia_portrait.jpg/256px-Johannes_Vermeer_-_Wikipedia_portrait.jpg",
    description: "Vermeer's mastery of light is on full display as a young woman opens a window, bathing the scene in cool morning light.",
  },
  {
    id: 7,
    metId: 436155,
    title: "Allegory of the Catholic Faith",
    artist: "Johannes Vermeer",
    year: "c. 1670–1672",
    medium: "Oil on canvas",
    dimensions: "114.3 × 88.9 cm",
    style: "Dutch Golden Age",
    origin: "Netherlands",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Johannes_Vermeer_-_Wikipedia_portrait.jpg/256px-Johannes_Vermeer_-_Wikipedia_portrait.jpg",
    description: "Vermeer's largest and most ambitious work, richly symbolic and drawing on Cesare Ripa's Iconologia.",
  },
  {
    id: 8,
    metId: 438722,
    title: "The Dance Class",
    artist: "Edgar Degas",
    year: "1874",
    medium: "Oil on canvas",
    dimensions: "83.5 × 77.2 cm",
    style: "Impressionism",
    origin: "France",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Edgar_Degas_%28self_portrait%29.jpg/256px-Edgar_Degas_%28self_portrait%29.jpg",
    description: "Degas captured the unglamorous reality behind ballet — young dancers rehearsing under a watchful maître de ballet.",
  },
  {
    id: 9,
    metId: 436947,
    title: "A Sunday on La Grande Jatte — Study",
    artist: "Georges Seurat",
    year: "1884",
    medium: "Oil on canvas",
    dimensions: "70.5 × 104.1 cm",
    style: "Pointillism",
    origin: "France",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Georges_Seurat.jpg/256px-Georges_Seurat.jpg",
    description: "A preparatory study for Seurat's monumental masterpiece, already showing his revolutionary optical colour mixing.",
  },
  {
    id: 10,
    metId: 459055,
    title: "The Monet Family in Their Garden",
    artist: "Édouard Manet",
    year: "1874",
    medium: "Oil on canvas",
    dimensions: "61 × 99.7 cm",
    style: "Impressionism",
    origin: "France",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Edgar_Degas_-_Edouard_Manet%2C_buste.jpg/256px-Edgar_Degas_-_Edouard_Manet%2C_buste.jpg",
    description: "Painted during a summer visit to Argenteuil, Manet captures Monet painting in his garden while Camille rests nearby.",
  },
  {
    id: 11,
    metId: 436532,
    title: "Roses",
    artist: "Vincent van Gogh",
    year: "1890",
    medium: "Oil on canvas",
    dimensions: "71.1 × 90.2 cm",
    style: "Post-Impressionism",
    origin: "Netherlands",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg/256px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_%28454045%29.jpg",
    description: "Among van Gogh's final works before leaving the asylum at Saint-Rémy, these roses burst with restless, joyful energy.",
  },
  {
    id: 12,
    metId: 436528,
    title: "Garden at Sainte-Adresse",
    artist: "Claude Monet",
    year: "1867",
    medium: "Oil on canvas",
    dimensions: "98.1 × 129.9 cm",
    style: "Impressionism",
    origin: "France",
    artist_portrait: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Claude_Monet_1899_Nadar_crop.jpg/256px-Claude_Monet_1899_Nadar_crop.jpg",
    description: "Monet's dazzling seaside garden scene, flooded with summer light, is considered a proto-Impressionist landmark.",
  },
];

export const getTrendingArtworks = () => artworks.slice(0, 5);